### ISSUE TITLE
User profile page

### ISSUE THREAD

**Issue by gchoy** [namelessprofit/project-1#7]

**Comment by namelessprofit** [comment]
<html>
<head>
<script>
function show(shown, hidden) {
  document.getElementById(shown).style.display='block';
  document.getElementById(hidden).style.display='none';
  return false;
}
</script>
</head>
<body>

  <div id="Page1">
    Content of page 1
    <a href="#" onclick="return show('Page2','Page1');">Show page 2</a>
  </div>

  <div id="Page2" style="display:none">
    Content of page 2
    <a href="#" onclick="return show('Page1','Page2');">Show page 1</a>
  </div>

</body>
</html>

example on how to create a new page

**Comment by gchoy** [comment]
Postpone to V2. 
V2 will have a user profile page
